### PR TITLE
Accep particle

### PR DESCRIPTION
**Pull request by stevendargaville**
Initial attempt at solving 12, the ability to specify the acceptable lost particles before termination

### CODE REVIEW

**Comment by stevendargaville** [comment]
My main concern is that I have modified one of the existing regression tests, and given the lack of regression tests I was reluctant to create an new one for what feels like a small change that should be tested in the unit tests. 

I modified a unit test in c997b5e to test the new settings, but that regression test was the only one I could find where I could explicitly do a comparison on the output xml by the python layer (modified in 
71eb099) and then 023a622 which tests the output of StatePoint.

I'm happy to ask the OpenMC dev team for some more guidance, but thought I would open this up for thoughts beforehand.

**Comment by stevendargaville** [comment]
Also this PR seems to pass all the unit and regression tests that were running on my machine on the develop branch (including those modified by this PR).

**Review by simondrichards — APPROVED** [review]
Code changes look good and unit test and regression test both pass.

**Comment by simondrichards** [comment]
PR merged, and I'm happy for the PR to be submitted to openmc-dev

**Pull request merged**
